[package]
name = "inx_video_util"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
eframe = { version = "0.29.1", default-features = false, features = ["glow", "default_fonts"] }
egui-video = "0.9.0"
